# Generated by Django 3.2 on 2021-07-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactmeus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=40)),
                ('phone', models.IntegerField()),
                ('subject', models.TextField(max_length=400)),
            ],
        ),
    ]
