# Generated by Django 3.2 on 2021-08-13 02:33

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='your_comment',
            field=tinymce.models.HTMLField(),
        ),
    ]
