# Generated by Django 3.2 on 2021-07-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40)),
                ('phone', models.IntegerField()),
                ('purpose', models.CharField(choices=[('Sales', 'Sales'), ('Traning', 'Traning'), ('Job', 'Job'), ('General Inquries', 'General Inquries')], default='select', max_length=100)),
                ('email', models.EmailField(default='example@gmail.com', max_length=50)),
                ('comment', models.TextField(max_length=700)),
                ('contact_by', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
